// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX8uiwHfeOh2RFX2y1ARZ1nvQCxaoQB0w',
    appId: '1:945351491433:web:e631cf1ed481e85f29c7f8',
    messagingSenderId: '945351491433',
    projectId: 'sos-emergency-app-7f7f8',
    authDomain: 'sos-emergency-app-7f7f8.firebaseapp.com',
    storageBucket: 'sos-emergency-app-7f7f8.firebasestorage.app',
    measurementId: 'G-RG3L7SY7FW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm9fNtJtVd-Ox7NNSlCoWerakcZKhTRBU',
    appId: '1:945351491433:android:87438ff920dfe0aa29c7f8',
    messagingSenderId: '945351491433',
    projectId: 'sos-emergency-app-7f7f8',
    storageBucket: 'sos-emergency-app-7f7f8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6yxkkqeW7ZrlpdJGoZ_6uvnX3YSaDHQk',
    appId: '1:945351491433:ios:ca2244c21d32533229c7f8',
    messagingSenderId: '945351491433',
    projectId: 'sos-emergency-app-7f7f8',
    storageBucket: 'sos-emergency-app-7f7f8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6yxkkqeW7ZrlpdJGoZ_6uvnX3YSaDHQk',
    appId: '1:945351491433:ios:ca2244c21d32533229c7f8',
    messagingSenderId: '945351491433',
    projectId: 'sos-emergency-app-7f7f8',
    storageBucket: 'sos-emergency-app-7f7f8.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCX8uiwHfeOh2RFX2y1ARZ1nvQCxaoQB0w',
    appId: '1:945351491433:web:33d19d2ca22862ac29c7f8',
    messagingSenderId: '945351491433',
    projectId: 'sos-emergency-app-7f7f8',
    authDomain: 'sos-emergency-app-7f7f8.firebaseapp.com',
    storageBucket: 'sos-emergency-app-7f7f8.firebasestorage.app',
    measurementId: 'G-PXM9GZC732',
  );
}
